[2025-02-20T23:53:19.493+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: listenbrainz_pipeline_duckdb.parse_json manual__2025-02-20T23:53:16.168640+00:00 [queued]>
[2025-02-20T23:53:19.519+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: listenbrainz_pipeline_duckdb.parse_json manual__2025-02-20T23:53:16.168640+00:00 [queued]>
[2025-02-20T23:53:19.519+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-02-20T23:53:19.519+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-02-20T23:53:19.520+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-02-20T23:53:19.563+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): parse_json> on 2025-02-20 23:53:16.168640+00:00
[2025-02-20T23:53:19.575+0000] {standard_task_runner.py:55} INFO - Started process 247 to run task
[2025-02-20T23:53:19.581+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'listenbrainz_pipeline_duckdb', 'parse_json', 'manual__2025-02-20T23:53:16.168640+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/listenbrainz_dag.py', '--cfg-path', '/tmp/tmp7rnlu_7p']
[2025-02-20T23:53:19.585+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask parse_json
[2025-02-20T23:53:19.773+0000] {task_command.py:388} INFO - Running <TaskInstance: listenbrainz_pipeline_duckdb.parse_json manual__2025-02-20T23:53:16.168640+00:00 [running]> on host ef724a9ffaa8
[2025-02-20T23:53:19.952+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=listenbrainz_pipeline_duckdb
AIRFLOW_CTX_TASK_ID=parse_json
AIRFLOW_CTX_EXECUTION_DATE=2025-02-20T23:53:16.168640+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-20T23:53:16.168640+00:00
[2025-02-20T23:53:19.954+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/listenbrainz_dag.py", line 47, in parse_json
    parse_json_to_csv(JSON_FILE_PATH, "/data/listens.csv")
  File "/opt/airflow/src/pipeline/unified_pipeline.py", line 43, in parse_json_to_csv
    with open(json_file, 'r', encoding='utf-8') as infile, \
FileNotFoundError: [Errno 2] No such file or directory: '../data/raw/sample-data.json'
[2025-02-20T23:53:19.975+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=listenbrainz_pipeline_duckdb, task_id=parse_json, execution_date=20250220T235316, start_date=20250220T235319, end_date=20250220T235319
[2025-02-20T23:53:19.996+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task parse_json ([Errno 2] No such file or directory: '../data/raw/sample-data.json'; 247)
[2025-02-20T23:53:20.033+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-02-20T23:53:20.116+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
