[2025-02-20T23:48:45.589+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: listenbrainz_pipeline_duckdb.parse_json manual__2025-02-20T23:48:43.444475+00:00 [queued]>
[2025-02-20T23:48:45.600+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: listenbrainz_pipeline_duckdb.parse_json manual__2025-02-20T23:48:43.444475+00:00 [queued]>
[2025-02-20T23:48:45.600+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-02-20T23:48:45.600+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-02-20T23:48:45.600+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-02-20T23:48:45.618+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): parse_json> on 2025-02-20 23:48:43.444475+00:00
[2025-02-20T23:48:45.623+0000] {standard_task_runner.py:55} INFO - Started process 241 to run task
[2025-02-20T23:48:45.626+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'listenbrainz_pipeline_duckdb', 'parse_json', 'manual__2025-02-20T23:48:43.444475+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/listenbrainz_dag.py', '--cfg-path', '/tmp/tmpkgky0hh4']
[2025-02-20T23:48:45.628+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask parse_json
[2025-02-20T23:48:45.736+0000] {task_command.py:388} INFO - Running <TaskInstance: listenbrainz_pipeline_duckdb.parse_json manual__2025-02-20T23:48:43.444475+00:00 [running]> on host 8fc7d7ce9abe
[2025-02-20T23:48:45.930+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=listenbrainz_pipeline_duckdb
AIRFLOW_CTX_TASK_ID=parse_json
AIRFLOW_CTX_EXECUTION_DATE=2025-02-20T23:48:43.444475+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-20T23:48:43.444475+00:00
[2025-02-20T23:48:45.931+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/listenbrainz_dag.py", line 47, in parse_json
    parse_json_to_csv(JSON_FILE_PATH, "/data/listens.csv")
  File "/opt/airflow/src/pipeline/unified_pipeline.py", line 43, in parse_json_to_csv
    with open(json_file, 'r', encoding='utf-8') as infile, \
FileNotFoundError: [Errno 2] No such file or directory: '../data/raw/sample-dtata.json'
[2025-02-20T23:48:45.950+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=listenbrainz_pipeline_duckdb, task_id=parse_json, execution_date=20250220T234843, start_date=20250220T234845, end_date=20250220T234845
[2025-02-20T23:48:45.968+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task parse_json ([Errno 2] No such file or directory: '../data/raw/sample-dtata.json'; 241)
[2025-02-20T23:48:45.998+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-02-20T23:48:46.044+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
